# Настройки подключения к PostgreSQL в Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk_db
spring.datasource.username=postgres
spring.datasource.password=6770
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Настройки Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Имя приложения
spring.application.name=demo
# Секретный ключ
jwt.secret=9a4f2c8d7e1b3a5f8c6d4e2b0a9f8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b

# Время жизни токена в миллисекундах
jwt.expirationMs=86400000

#Подключаем Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
# Вывод и форматирование SQL-запросов в консоли IDE

spring.jpa.properties.hibernate.format_sql=true

# Включаем детальную статистику Hibernate (покажет число SQL-запросов и время)
spring.jpa.properties.hibernate.generate_statistics=true